#!/usr/bin/env bash
#ddev-generated

## Description: Build Shopware Administration and Storefront
## Usage: build [static|plugin] [plugins...]
## Example: "ddev build" or "ddev build static" or "ddev build plugin SwagPluginA"

set -euo pipefail

SCRIPT_DIR="$(dirname "$0")"

echo
echo "=== Building Administration ==="
echo

"$SCRIPT_DIR/admin-build" "$@"

echo
echo "=== Building Storefront ==="
echo

"$SCRIPT_DIR/storefront-build" "$@"

echo
echo "=== Build completed ==="
echo
